### ISSUE TITLE
Issue1: Bug in MessageHandler::read 

### ISSUE THREAD

**Issue by DelVecchioAndrea** [BE-Mesh/esp32-ble-mesh#17]
Riporto il log del bug sulla read dell MessageHandler nella propagazione dei routing update messages.

> E (153026) GATT_SERVER: In routing update transmission callback
E (153026) GATT_SERVER: In routing update transmission callback. Beginning to parse the arguments
E (153036) GATT_SERVER: In routing update transmission callback. Ended to parse the arguments
E (153046) GATT_SERVER: Ended updating the neighbours
E (153046) GATT_CLIENT: Success writing the char: 0
Ho un totale di m_rx_entries: -1[unserialize] received id no. 00
E (153066) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -2[unserialize] received id no. 00
E (153086) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -3[unserialize] received id no. 00
E (153096) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -4[unserialize] received id no. 00
E (153116) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -5[unserialize] received id no. 00
E (153126) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -6[unserialize] received id no. 00
E (153146) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -7[unserialize] received id no. 00
E (153166) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -8[unserialize] received id no. 00
E (153176) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -9[unserialize] received id no. 00
E (153196) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -10[unserialize] received id no. 00
E (153216) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -11[unserialize] received id no. 00
E (153226) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -12[unserialize] received id no. 00
E (153246) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -13[unserialize] received id no. 00
E (153266) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -14[unserialize] received id no. 00
E (153276) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -15[unserialize] received id no. 00
E (153296) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -16[unserialize] received id no. 00
E (153306) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -17[unserialize] received id no. 00
E (153326) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -18[unserialize] received id no. 00
E (153346) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -19[unserialize] received id no. 00
E (153356) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -20[unserialize] received id no. 00
E (153376) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -21[unserialize] received id no. 00
E (153396) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -22[unserialize] received id no. 00
E (153406) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -23[unserialize] received id no. 00
E (153426) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -24[unserialize] received id no. 00
E (153446) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -25[unserialize] received id no. 00
E (153456) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -26[unserialize] received id no. 00
E (153476) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -27[unserialize] received id no. 00
E (153496) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -28[unserialize] received id no. 00
E (153506) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -29[unserialize] received id no. 00
E (153526) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -30[unserialize] received id no. 00
E (153536) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -31[unserialize] received id no. 00
E (153556) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -32[unserialize] received id no. 00
E (153576) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -33[unserialize] received id no. 00
E (153586) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -34[unserialize] received id no. 00
E (153606) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -35[unserialize] received id no. 00
E (153626) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -36[unserialize] received id no. 00
E (153636) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -37[unserialize] received id no. 00
E (153656) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -38[unserialize] received id no. 00
E (153676) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -39[unserialize] received id no. 00
E (153686) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -40[unserialize] received id no. 00
E (153706) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -41[unserialize] received id no. 00
E (153726) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -42[unserialize] received id no. 00
E (153736) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -43[unserialize] received id no. 00
E (153756) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -44[unserialize] received id no. 00
E (153766) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -45[unserialize] received id no. 00
E (153786) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -46[unserialize] received id no. 00
E (153806) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -47[unserialize] received id no. 00
E (153816) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -48[unserialize] received id no. 00
E (153836) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response
Ho un totale di m_rx_entries: -49[unserialize] received id no. 00
E (153856) GATT_SERVER: Someone wants to discover my routing table and I prepare a routing discovery response

**Comment by EmanueleGiacomini** [comment]
Il problema era legato ad un possibile caso in cui la funzione unserialize ritornasse un puntatore a NULL. In quel caso la funzione di handle procedeva con una __continue__ che terminava il loop e passava all'elemento successivo senza effettuare operazioni su m_rx_entries.

__La soluzione va testata.__

**Comment by EmanueleGiacomini** [comment]
427db701a40c63f23c4ad2a7d54706cc70a32432
Link al commit

**Comment by Thecave3** [comment]
Questa soluzione ha funzionato?

**Comment by Thecave3** [comment]
> Il problema era legato ad un possibile caso in cui la funzione unserialize ritornasse un puntatore a NULL. In quel caso la funzione di handle procedeva con una **continue** che terminava il loop e passava all'elemento successivo senza effettuare operazioni su m_rx_entries.
> 
> **La soluzione va testata.**

Ha funzionato?

**Comment by DelVecchioAndrea** [comment]
Non ho avuto ancora modo di testarla. Stiamo risolvendo dei bug nello strato basso
