### ISSUE TITLE
issue:2 Bug in struttura scan_res e connectTo 

### ISSUE THREAD

**Issue by DelVecchioAndrea** [BE-Mesh/esp32-ble-mesh#18]
In fase di scanning il dispositivo individua molti più dispositivi di quelli che sono presenti. 
Una possibilità è che la struttura scan_res contenga valori non inizializzati e quindi una volta che si ha accesso ai suoi elementi vengono letti valori che non corrispondono ad alcun dato significativo.

> 
E (20087) GATT_CLIENT: End of scanning!
E (20087) GATT_CLIENT: Found this server at the end of scanning: address:
I (20087) GATT_CLIENT: 00 00 00 00 23 09 
E (20097) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 201
E (20097) GATT_CLIENT: Found this server at the end of scanning: address:
I (20107) GATT_CLIENT: 43 f7 b5 00 00 00 
E (20107) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 202
E (20117) GATT_CLIENT: Found this server at the end of scanning: address:
I (20127) GATT_CLIENT: 70 a5 fb 3f 15 a8 
E (20127) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 202
E (20137) GATT_CLIENT: Found this server at the end of scanning: address:
I (20147) GATT_CLIENT: 00 00 00 00 70 f5 
E (20147) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 197
E (20157) GATT_CLIENT: Found this server at the end of scanning: address:
I (20167) GATT_CLIENT: 00 00 00 00 00 00 
E (20167) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 202
E (20177) GATT_CLIENT: Found this server at the end of scanning: address:
I (20187) GATT_CLIENT: 40 a4 fb 3f 15 a8 
E (20187) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 203
E (20197) GATT_CLIENT: Found this server at the end of scanning: address:
I (20197) GATT_CLIENT: 28 a6 fb 3f 00 00 
E (20207) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 203
E (20217) GATT_CLIENT: Found this server at the end of scanning: address:
I (20217) GATT_CLIENT: 41 a6 fb 3f 40 a6 
E (20227) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 203
E (20237) GATT_CLIENT: Found this server at the end of scanning: address:
I (20237) GATT_CLIENT: 24 6f 28 97 4c 32 
E (20247) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 201
E (20247) GATT_CLIENT: Found this server at the end of scanning: address:
I (20257) GATT_CLIENT: fc ff ff ff 21 a7 
E (20267) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 202
E (20267) GATT_CLIENT: Found this server at the end of scanning: address:
I (20277) GATT_CLIENT: 40 a6 fb 3f 00 00 
E (20287) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 202
E (20287) GATT_CLIENT: Out of the loop: we have collected a device list of: 11 elements
E (20297) GATT_CLIENT: Chosen server in pos: 0
W (50307) BT_APPL: bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x0100
I (50307) GATT_CLIENT: ESP_GATTC_DISCONNECT_EVT, reason = 256
E (50317) GATT_CLIENT: open failed, status 13

Questo è il log della parte client. 

Questo è , invece, quello della parte server:

> E (22147) GATT_CLIENT: REMOVING CLIENT!
E (22147) GATT_CLIENT: I'M A SERVER!!!
E (22157) BT_APPL: bta_gattc_deregister Deregister Failedm unknown client cif
E (22157) BT_APPL: application already registered.

E (22167) GATT_SERVER: reg app failed, app_id a45c, status 144

Questo è il log della parte server. Il problema dei mutipli device si presenta solo lato client.

**Comment by DelVecchioAndrea** [comment]
Ho provato a scrivere un array di 6 numeri sul server su una caratteristica nota e questo è quello che ho ottenuto. Ho provato a scrivere più volte per essere sicuro.

E (20297) GATT_CLIENT: Finished installing all things
E (20297) GATT_CLIENT: I'm about to write something on the server
E (20307) GATT_CLIENT: Error writing the char: ffffffff
E (20307) GATT_CLIENT: Error writing the char: ffffffff
E (20307) GATT_CLIENT: Error writing the char: ffffffff
E (20307) GATT_CLIENT: Error writing the char: ffffffff
E (20307) GATT_CLIENT: Error writing the char: ffffffff

**Comment by DelVecchioAndrea** [comment]
Ho provato la versione fixata. scan_seq viene sempre tenuto a 0 e non aumenta mai. E' normale?


Questo è il log
> E (35168) GATT_CLIENT: Out of the loop: we have collected a device list of: 0 elements
E (35168) GATT_CLIENT: REMOVING CLIENT!
E (35168) GATT_CLIENT: I'M A SERVER!!!
E (35178) BT_APPL: bta_gattc_deregister Deregister Failedm unknown client cif
E (35178) BT_APPL: application already registered.

E (35188) GATT_SERVER: reg app failed, app_id 0000, status 144


//Questo è il codice della funzione che usa la struttura scan_res
`void Callback::endscanning_callback(device* device_list,uint8_t count){
        int i;
        

        //We perform some integrity check.
        if(device_list == NULL)
            return;

        if(count > SCAN_LIMIT){
            ESP_LOGE(GATTC_TAG,"Error in endscanning_callback. Device number: %d exceed the SCAN_LIMIT: %d",
                                count,SCAN_LIMIT);
            return;
        }

        for(i = 0; i<count; i++){
            
            uint8_t* addr = device_list[i].mac;
            uint8_t type = device_list[i].addr_type;
            uint8_t num_clients = device_list[i].clients_num;
            uint8_t signal_strength = device_list[i].rssi;
            ESP_LOGE(GATTC_TAG,"Found this server at the end of scanning: address:");
            esp_log_buffer_hex(GATTC_TAG,addr, MAC_ADDRESS_SIZE);
            ESP_LOGE(GATTC_TAG,"type: %d num_clients: %d signal strength: %d",type,num_clients,signal_strength);
        
        }
        ESP_LOGE(GATTC_TAG, "Out of the loop: we have collected a device list of: %d elements",count);
        connection_policy_t policy = Maximum_rssi_value_policy;
        if (count == 0){
            //If no server is found we become a server ourselves
            becomeServer();
            //ESP_LOGE(GATTC_TAG,"I become a server");
            return;
        }
        else{
            int server_pos = connect_to_server(device_list,count,policy);
            if(server_pos == -1){
                ESP_LOGE(GATTC_TAG, "Unable to connect to any server");
                return;
            }
            else{
                ESP_LOGE(GATTC_TAG,"Chosen server in pos: %d",server_pos);
                //We initialize client object.
                init_callback(CLIENT);
                return;
            }
        }`

**Comment by RickyMexx** [comment]
Scan_seq viene resettato a 0 ogni volta che una connessione va a buon fine. Quindi al momento della callback dovrebbe darti il valore giusto di device. Prova a ciclare fino a 10 invece di count e guarda il valore di dev_name/mac che restituisce (non vorrei che in parallelo vada a settare la variabile a zero).

**Comment by DelVecchioAndrea** [comment]
Crasha


>E (7079) GATT_CLIENT: Found this server at the end of scanning: address:
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x4000c2f9  PS      : 0x00060930  A0      : 0x800d4442  A1      : 0x3ffcba50  
A2      : 0x3ffcba60  A3      : 0x00000000  A4      : 0x00000008  A5      : 0x3ffcba60  
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x3ffcb750  
A10     : 0x00000054  A11     : 0xffffffff  A12     : 0x00000001  A13     : 0x3ffcb960  
A14     : 0x00000054  A15     : 0x3ffcb960  SAR     : 0x00000004  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  

ELF file SHA256: 7f4e7789962fec19c4dfd84e78122bef670346b7733f313fa79719dd07528422

Backtrace: 0x4000c2f6:0x3ffcba50 |<-CORRUPTED

Rebooting...

**Comment by RickyMexx** [comment]
Ok continua con il resto, mi metto a debuggare io
