### ISSUE TITLE
Problema scrittura caratteristiche nella comunicazione server-server

### ISSUE THREAD

**Issue by DelVecchioAndrea** [BE-Mesh/esp32-ble-mesh#23]
Sto riscontrando dei problemi per quanto riguarda la comunicazione server-server per quanto riguarda la scrittura delle caratteristiche. 
I due server riescono a connettersi tra di loro e, di conseguenza, vengono istanziati i rispettivi internal clients. 
Quando due server si connettono si scambiano immediatamente due pacchetti ROUTING_DISCOVERY_REQ_ID. Questo scambio avviene tramite scrittura su caratteristiche. Qui sta l'intoppo: entrambi i server riescono a scrivere ma nessuno dei due riceve la notifica dell'avvenuta scrittura.
Di seguito i log dei due server:

> E (16238) GATT_CLIENT: Chosen server in pos: 0
E (16248) GATT_SERVER: I want to discover some routing table
E (16248) GATT_SERVER: In routing discovery request transmission callback
E (16258) GATT_CLIENT: Writing attempt number: 0
E (16268) GATT_CLIENT: Error writing the char: ffffffff
E (16268) GATT_CLIENT: Writing attempt number: 1
E (16278) GATT_CLIENT: Error writing the char: ffffffff
E (16278) GATT_CLIENT: Writing attempt number: 2
E (16288) GATT_CLIENT: Error writing the char: ffffffff
E (16298) GATT_CLIENT: Writing attempt number: 3
E (16298) GATT_CLIENT: Error writing the char: ffffffff
E (16308) GATT_CLIENT: Writing attempt number: 4
E (16308) GATT_CLIENT: Error writing the char: ffffffff
E (16318) GATT_CLIENT: Writing attempt number: 5
E (16318) GATT_CLIENT: Error writing the char: ffffffff
E (16328) GATT_CLIENT: Writing attempt number: 6
E (16328) GATT_CLIENT: Error writing the char: ffffffff
E (16338) GATT_CLIENT: Writing attempt number: 7
E (16348) GATT_CLIENT: Error writing the char: ffffffff
E (16348) GATT_CLIENT: Writing attempt number: 8
E (16358) GATT_CLIENT: Error writing the char: ffffffff
E (16358) GATT_CLIENT: Writing attempt number: 9
E (16368) GATT_CLIENT: Success writing the char: 0
I (16418) GATT_SERVER: ESP_GATTS_CONNECT_EVT, conn_id = 0
I (16418) GATT_SERVER: 24 6f 28 97 4c 32 
W (16428) BT_L2CAP: l2cble_start_conn_update, the last connection update command still pending.
I (16418) GATT_CLIENT: ESP_GATTC_OPEN_EVT conn_id 0, if 4, status 0, mtu 23
I (16438) GATT_CLIENT: REMOTE MAC:
I (16448) GATT_CLIENT: 24 6f 28 97 4c 32 
E (16448) BT_L2CAP: There are two connection parameter requests that are being updated, please try later 
E (16458) BT_APPL: Update connection parameters failed!
W (16468) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16478) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (16488) GATT_CLIENT: update connection params status = 13, min_int = 16, max_int = 32,conn_int = 12,latency = 0, timeout = 600
W (16488) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16498) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (16578) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (17018) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (17538) GATT_CLIENT: Status 0, MTU 500, conn_id 0
I (17538) GATT_CLIENT: SEARCH RES: conn_id = 0 is primary service 1
I (17538) GATT_CLIENT: start handle 40 end handle 65535 current handle value 40
I (17548) GATT_CLIENT: UUID16: ff
I (17698) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive notify value:
I (17698) GATT_CLIENT: aa 28 29 2a 2b 2c 2d 2e 2f 
I (17698) GATT_CLIENT: write descr success
I (17778) GATT_CLIENT: write descr success

Server 2

> E (16137) GATT_CLIENT: Chosen server in pos: 0
E (16147) GATT_SERVER: I want to discover some routing table
E (16147) GATT_SERVER: In routing discovery request transmission callback
E (16157) GATT_CLIENT: Writing attempt number: 0
E (16167) GATT_CLIENT: Success writing the char: 0
E (16167) BT_APPL: bta_gattc_process_api_open Failed, unknown client_if: 255

Come evidenziato dall'ultimo log credo ci sia un errore su uno dei gatt_if. Ma non saprei onestamente.

I due server provano a mandarsi pacchetti ROUTING_DISCOVERY_REQ_ID "simultaneamente".

**Comment by DelVecchioAndrea** [comment]
Nuovo esperimento:

Log server 1:

> E (15938) GATT_CLIENT: Result is -> 1
E (15938) GATT_CLIENT: Already known device!
I (15948) GATT_CLIENT: 37 24 f3 80 9e 8e 
I (16008) GATT_CLIENT: 37 24 f3 80 9e 8e 
I (16038) GATT_CLIENT: 72 a4 a1 cd 68 05 
I (16048) GATT_SERVER: GATT_WRITE_EVT, handle = 43, value len = 2, value :
I (16048) GATT_SERVER: 01 00 
I (16048) GATT_SERVER: notify enable
I (16058) GATT_SERVER: ESP_GATTS_CONF_EVT, status = 0, attr_handle 42
I (16108) GATT_CLIENT: 37 24 f3 80 9e 8e 
I (16128) GATT_SERVER: GATT_WRITE_EVT, handle = 43, value len = 2, value :
I (16128) GATT_SERVER: 04 00 
E (16128) GATT_SERVER: A new server is connected
E (16138) GATT_SERVER: I want to discover some routing table
E (16148) GATT_SERVER: In routing discovery request transmission callback
E (16148) GATT_CLIENT: Writing attempt number: 0
E (16148) GATT_CLIENT: Found this server at the end of scanning: address:
E (16158) GATT_CLIENT: Error writing the char: ffffffff
I (16168) GATT_CLIENT: 24 6f 28 10 7d ae 
E (16168) GATT_CLIENT: Writing attempt number: 1
E (16178) GATT_CLIENT: type: 0 num_clients: 1 signal strength: 217
E (16178) GATT_CLIENT: Error writing the char: ffffffff
E (16188) GATT_CLIENT: Out of the loop: we have collected a device list of: 1 elements
E (16188) GATT_CLIENT: Writing attempt number: 2
E (16208) GATT_CLIENT: Error writing the char: ffffffff
E (16198) GATT_CLIENT: Chosen server in pos: 0
E (16208) GATT_CLIENT: Writing attempt number: 3
E (16218) GATT_SERVER: I want to discover some routing table
E (16218) GATT_CLIENT: Error writing the char: ffffffff
E (16228) GATT_SERVER: In routing discovery request transmission callback
E (16238) GATT_CLIENT: Writing attempt number: 4
W (16248) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
E (16248) GATT_CLIENT: Writing attempt number: 0
W (16258) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
E (16248) GATT_CLIENT: Error writing the char: ffffffff
W (16268) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
E (16258) GATT_CLIENT: Writing attempt number: 1
W (16278) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
E (16268) GATT_CLIENT: Writing attempt number: 5
E (16288) GATT_CLIENT: Writing attempt number: 2
E (16298) GATT_CLIENT: Error writing the char: ffffffff
E (16308) GATT_CLIENT: Writing attempt number: 6
E (16308) GATT_CLIENT: Error writing the char: ffffffff
E (16308) BT_APPL: bta_gattc_process_api_open Failed, unknown client_if: 255
E (16308) GATT_CLIENT: Writing attempt number: 3
E (16318) GATT_CLIENT: Writing attempt number: 7
E (16338) GATT_CLIENT: Writing attempt number: 4
E (16338) GATT_CLIENT: Error writing the char: ffffffff
E (16348) GATT_CLIENT: Writing attempt number: 5
E (16348) GATT_CLIENT: Writing attempt number: 8
E (16358) GATT_CLIENT: Writing attempt number: 6
E (16358) GATT_CLIENT: Error writing the char: ffffffff
E (16368) GATT_CLIENT: Writing attempt number: 7
E (16378) GATT_CLIENT: Writing attempt number: 9
E (16378) GATT_CLIENT: Writing attempt number: 8
E (16388) GATT_CLIENT: Error writing the char: ffffffff
E (16388) GATT_CLIENT: Writing attempt number: 9
E (16388) GATT_CLIENT: Writing attempt number: 10
E (16398) GATT_CLIENT: Writing attempt number: 10
E (16398) GATT_CLIENT: Error writing the char: ffffffff
E (16408) GATT_CLIENT: Writing attempt number: 11
E (16418) GATT_CLIENT: Writing attempt number: 11
E (16428) GATT_CLIENT: Writing attempt number: 12
E (16428) GATT_CLIENT: Error writing the char: ffffffff
E (16438) GATT_CLIENT: Writing attempt number: 13
E (16438) GATT_CLIENT: Writing attempt number: 12
E (16438) GATT_CLIENT: Writing attempt number: 14
E (16448) GATT_CLIENT: Error writing the char: ffffffff
E (16458) GATT_CLIENT: Writing attempt number: 15
E (16458) GATT_CLIENT: Writing attempt number: 13
E (16468) GATT_CLIENT: Writing attempt number: 16
E (16478) GATT_CLIENT: Error writing the char: ffffffff
E (16478) GATT_CLIENT: Writing attempt number: 17
E (16478) GATT_CLIENT: Writing attempt number: 14
E (16488) GATT_CLIENT: Writing attempt number: 18
E (16488) GATT_CLIENT: Error writing the char: ffffffff
E (16498) GATT_CLIENT: Writing attempt number: 19
E (16508) GATT_CLIENT: Writing attempt number: 15
E (16508) GATT_CLIENT: Error writing the char: ffffffff
E (16518) GATT_CLIENT: Writing attempt number: 16
E (16528) GATT_CLIENT: Error writing the char: ffffffff
E (16528) GATT_CLIENT: Writing attempt number: 17
E (16538) GATT_CLIENT: Error writing the char: ffffffff
E (16538) GATT_CLIENT: Writing attempt number: 18
E (16548) GATT_CLIENT: Error writing the char: ffffffff
E (16548) GATT_CLIENT: Writing attempt number: 19
E (16558) GATT_CLIENT: Error writing the char: ffffffff

Log server 2:

> I (16148) GATT_CLIENT: 24 6f 28 97 4c 32 
E (16158) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 217
E (16158) GATT_CLIENT: Out of the loop: we have collected a device list of: 2 elements
E (16168) GATT_CLIENT: Chosen server in pos: 0
E (16178) GATT_SERVER: I want to discover some routing table
E (16188) GATT_SERVER: In routing discovery request transmission callback
E (16188) GATT_CLIENT: Writing attempt number: 0
E (16198) GATT_CLIENT: Error writing the char: ffffffff
E (16198) GATT_CLIENT: Writing attempt number: 1
E (16208) GATT_CLIENT: Error writing the char: ffffffff
E (16208) GATT_CLIENT: Writing attempt number: 2
E (16218) GATT_CLIENT: Success writing the char: 0
I (16268) GATT_SERVER: ESP_GATTS_CONNECT_EVT, conn_id = 0
I (16268) GATT_SERVER: 24 6f 28 97 4c 32 
I (16268) GATT_CLIENT: ESP_GATTC_OPEN_EVT conn_id 0, if 4, status 0, mtu 23
I (16278) GATT_CLIENT: REMOTE MAC:
I (16278) GATT_CLIENT: 24 6f 28 97 4c 32 
W (16298) BT_L2CAP: l2cble_start_conn_update, the last connection update command still pending.
W (16298) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16308) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
W (16328) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16328) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (16458) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (16818) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (17338) GATT_CLIENT: Status 0, MTU 500, conn_id 0
I (17338) GATT_CLIENT: SEARCH RES: conn_id = 0 is primary service 1
I (17338) GATT_CLIENT: start handle 40 end handle 65535 current handle value 40
I (17348) GATT_CLIENT: UUID16: ff
I (17498) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive notify value:
I (17508) GATT_CLIENT: aa 28 29 2a 2b 2c 2d 2e 2f 
I (17508) GATT_CLIENT: write descr success
I (17578) GATT_CLIENT: write descr success

**Comment by DelVecchioAndrea** [comment]
Ho testato la comunicazione tra due server con le nuove callback installate. E il comportamento è questo. Ho inserito dei log per capire quale delle due callback(attiva e passiva) venisse invocata.
L'obiettivo era quello di inviare un buffer di 1,2,3,4,5,6. 

L'evento di scrittura non viene registrato da nessuno dei due ma solamente quello di notifica.

Server 1

> E (16148) GATT_CLIENT: Chosen server in pos: 0
I (16298) GATT_SERVER: ESP_GATTS_CONNECT_EVT, conn_id = 0
I (16298) GATT_SERVER: 24 6f 28 97 4c 32 
I (16298) GATT_CLIENT: ESP_GATTC_OPEN_EVT conn_id 0, if 4, status 0, mtu 23
I (16298) GATT_CLIENT: REMOTE MAC:
I (16308) GATT_CLIENT: 24 6f 28 97 4c 32 
E (16308) GATT_SERVER: In ssc_active_callback. writing
E (16318) GATT_CLIENT: Writing attempt number: 0
E (16318) GATT_CLIENT: Success writing the char: 0
W (16328) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16338) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
W (16358) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16358) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (16488) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (16888) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
E (17328) BT_GATT: gatt_act_write() failed op_code=0x52 rt=135
I (17328) GATT_CLIENT: Status 0, MTU 500, conn_id 0
E (17328) GATT_CLIENT: write char failed, error status = 87
I (17338) GATT_CLIENT: SEARCH RES: conn_id = 0 is primary service 1
I (17338) GATT_CLIENT: start handle 40 end handle 65535 current handle value 40
I (17348) GATT_CLIENT: UUID16: ff
I (17488) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive notify value:
I (17488) GATT_CLIENT: aa 28 29 2a 2b 2c 2d 2e 2f 
I (17488) GATT_CLIENT: write descr success
I (17568) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive indicate value:
I (17568) GATT_CLIENT: 01 02 03 04 05 06 
I (17568) GATT_CLIENT: write descr success
I (17848) GATT_SERVER: ESP_GATTS_MTU_EVT, MTU 500
I (18008) GATT_SERVER: GATT_WRITE_EVT, handle = 43, value len = 2, value :
I (18008) GATT_SERVER: 01 00 
I (18008) GATT_SERVER: notify enable
I (18008) GATT_SERVER: ESP_GATTS_CONF_EVT, status = 0, attr_handle 42
I (18088) GATT_SERVER: GATT_WRITE_EVT, handle = 43, value len = 2, value :
I (18088) GATT_SERVER: 04 00 
E (18088) GATT_SERVER: A new server is connected
E (18088) GATT_SERVER: In ssc_passive_callback. Sending a notification
E (18098) GATT_SERVER: In send notification conn_id: 0 characteristic: 2
W (18118) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (18118) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
W (18128) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (18128) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (18168) GATT_SERVER: ESP_GATTS_CONF_EVT, status = 0, attr_handle 42

Server 2

> I (15917) GATT_CLIENT: 7a 83 27 27 b3 70 
I (15927) GATT_SERVER: ESP_GATTS_CONNECT_EVT, conn_id = 0
I (15927) GATT_SERVER: 24 6f 28 10 7d ae 
I (15937) GATT_CLIENT: 60 fd 64 ea cf 04 
W (15937) BT_L2CAP: l2cble_start_conn_update, the last connection update command still pending.
W (15947) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (15957) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (15987) GATT_CLIENT: 24 f5 d9 6d d7 d1 
I (16047) GATT_CLIENT: update connection params status = 0, min_int = 0, max_int = 0,conn_int = 32,latency = 0, timeout = 400
I (16087) GATT_CLIENT: 24 f5 d9 6d d7 d1 
E (16157) GATT_CLIENT: Found this server at the end of scanning: address:
I (16157) GATT_CLIENT: 24 6f 28 10 7d ae 
E (16157) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 216
E (16167) GATT_CLIENT: Out of the loop: we have collected a device list of: 1 elements
E (16177) GATT_CLIENT: Chosen server in pos: 0
W (16187) BT_L2CAP: l2cble_start_conn_update, the last connection update command still pending.
I (16197) GATT_CLIENT: ESP_GATTC_OPEN_EVT conn_id 0, if 4, status 0, mtu 23
I (16197) GATT_CLIENT: REMOTE MAC:
I (16197) GATT_CLIENT: 24 6f 28 10 7d ae 
E (16207) GATT_SERVER: In ssc_active_callback. writing
E (16217) GATT_CLIENT: Writing attempt number: 0
W (16217) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
E (16217) GATT_CLIENT: Success writing the char: 0
W (16227) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (16847) GATT_SERVER: ESP_GATTS_MTU_EVT, MTU 500
I (17007) GATT_SERVER: GATT_WRITE_EVT, handle = 43, value len = 2, value :
I (17007) GATT_SERVER: 01 00 
I (17007) GATT_SERVER: notify enable
I (17017) GATT_SERVER: ESP_GATTS_CONF_EVT, status = 0, attr_handle 42
I (17047) GATT_CLIENT: update connection params status = 16, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (17087) GATT_SERVER: GATT_WRITE_EVT, handle = 43, value len = 2, value :
I (17087) GATT_SERVER: 04 00 
E (17087) GATT_SERVER: A new server is connected
E (17097) GATT_SERVER: In ssc_passive_callback. Sending a notification
E (17097) GATT_SERVER: In send notification conn_id: 0 characteristic: 2
W (17117) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (17117) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
W (17137) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (17137) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (17167) GATT_SERVER: ESP_GATTS_CONF_EVT, status = 0, attr_handle 42
E (17447) BT_GATT: gatt_act_write() failed op_code=0x52 rt=135
I (17447) GATT_CLIENT: Status 0, MTU 500, conn_id 0
E (17447) GATT_CLIENT: write char failed, error status = 87
I (17457) GATT_CLIENT: SEARCH RES: conn_id = 0 is primary service 1
I (17457) GATT_CLIENT: start handle 40 end handle 65535 current handle value 40
I (17467) GATT_CLIENT: UUID16: ff
I (17607) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive notify value:
I (17617) GATT_CLIENT: aa 28 29 2a 2b 2c 2d 2e 2f 
I (17617) GATT_CLIENT: write descr success
I (17687) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive indicate value:
I (17687) GATT_CLIENT: 01 02 03 04 05 06 
I (17687) GATT_CLIENT: write descr success

**Comment by RickyMexx** [comment]
Nuovo log con problema, server fisso [PASSIVO] + server con internal_client che si collega [ATTIVO].
Codice client attivo:

>E (16436) GATT_SERVER: In ssc_active_callback. writing
E (16436) GATT_CLIENT: Writing attempt number: 0
E (16446) GATT_CLIENT: Success writing the char: 0
W (16436) BT_L2CAP: l2cble_start_conn_update, the last connection update command still pending.
W (16456) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16466) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
W (16486) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16486) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (16566) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (17006) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
E (17566) BT_GATT: gatt_act_write() failed op_code=0x52 rt=135
I (17566) GATT_CLIENT: Status 0, MTU 500, conn_id 0
E (17576) GATT_CLIENT: write char failed, error status = 87
I (17576) GATT_CLIENT: SEARCH RES: conn_id = 0 is primary service 1
I (17576) GATT_CLIENT: start handle 40 end handle 65535 current handle value 40
I (17586) GATT_CLIENT: UUID16: ff
I (17726) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive notify value:
I (17736) GATT_CLIENT: aa 28 29 2a 2b 2c 2d 2e 2f 
I (17736) GATT_CLIENT: write descr success
I (17806) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive indicate value:
I (17806) GATT_CLIENT: 01 02 03 04 05 06 
I (17806) GATT_CLIENT: write descr success

**Comment by RickyMexx** [comment]
Ho risolto il problema della comunicazione server-server. Ora il passivo invia la notifica e l'attivo scrive con la write_chr. Rimane un problema sulla write_chr dell'attivo, ovvero i primi 4 byte corrispondono sempre a "24 37 40 3f " a prescindere dal buffer inviato e dalla sua lunghezza. Ad esempio, scrivendo [1,1,1,1,1,1] il server andrà a leggere:  GATT_SERVER: 24 37 40 3f 01 01 . Come vedi a partire dal quinto byte il buffer ha i valori originali.

Mi sono perso qualche magheggio nelle callback oppure è un nuovo comportamento anomalo?
Pulla per gli update.

**Comment by DelVecchioAndrea** [comment]
Non c'è nessun magheggio nelle callback. E' un nuovo comportamento anomalo. 
C'è un altro problema: le variabili conn_device_s1, conn_device_s2 e conn_device_s3 non vengono più settate a true. Questo non mi permette di ottenere i connection_id e i gatt_if degli internal client.


Server 1:

> E (16129) GATT_CLIENT: Found this server at the end of scanning: address:
I (16129) GATT_CLIENT: 24 6f 28 97 4c 32 
E (16129) GATT_CLIENT: type: 0 num_clients: 1 signal strength: 201
E (16139) GATT_CLIENT: Out of the loop: we have collected a device list of: 1 elements
E (16149) GATT_CLIENT: Chosen server in pos: 0
E (16159) BT_APPL: bta_gattc_process_api_open Failed, unknown client_if: 255
I (16459) GATT_SERVER: ESP_GATTS_MTU_EVT, MTU 500
I (16619) GATT_SERVER: GATT_WRITE_EVT, handle = 43, value len = 2, value :
I (16619) GATT_SERVER: 01 00 
I (16619) GATT_SERVER: notify enable
I (16629) GATT_SERVER: ESP_GATTS_CONF_EVT, status = 0, attr_handle 42
I (16699) GATT_SERVER: GATT_WRITE_EVT, handle = 43, value len = 2, value :
I (16699) GATT_SERVER: 04 00 
E (16709) GATT_SERVER: A new server is connected
E (16709) GATT_SERVER: Adding a neighbour: 66, 255, 255
E (16719) GATT_SERVER: Adding a new neighbour 
E (16719) GATT_SERVER: In ssc_passive_callback. Sending a notification
E (16729) GATT_SERVER: In send notification conn_id: 0 characteristic: 2
W (16739) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16739) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (16749) GATT_CLIENT: update connection params status = 16, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
W (16759) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16769) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (16789) GATT_SERVER: GATT_WRITE_EVT, handle = 42, value len = 6, value :
I (16789) GATT_SERVER: 30 bb fc 3f dc 00 
I (16819) GATT_SERVER: ESP_GATTS_CONF_EVT, status = 0, attr_handle 42

Server 2:

> E (16258) GATT_CLIENT: Found this server at the end of scanning: address:
I (16258) GATT_CLIENT: 24 6f 28 10 7d ae 
E (16268) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 204
E (16278) GATT_CLIENT: Out of the loop: we have collected a device list of: 1 elements
E (16278) GATT_CLIENT: Chosen server in pos: 0
I (16358) GATT_SERVER: ESP_GATTS_CONNECT_EVT, conn_id = 0
I (16358) GATT_SERVER: 24 6f 28 10 7d ae 
E (16358) GATT_SERVER: Added an entry to the routing table: 
E (16368) GATT_SERVER: Sending routing updates to the neighbour list
E (16368) GATT_SERVER: Preparing to send the update packets to all neighbours
E (16388) GATT_SERVER: Ended updating the neighbours
I (16388) GATT_CLIENT: ESP_GATTC_OPEN_EVT conn_id 0, if 4, status 0, mtu 23
I (16398) GATT_CLIENT: REMOTE MAC:
I (16398) GATT_CLIENT: 24 6f 28 10 7d ae 
W (16408) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16418) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
W (16428) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16428) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (16568) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (16968) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (17368) GATT_CLIENT: Status 0, MTU 500, conn_id 0
I (17368) GATT_CLIENT: SEARCH RES: conn_id = 0 is primary service 1
I (17368) GATT_CLIENT: start handle 40 end handle 65535 current handle value 40
I (17378) GATT_CLIENT: UUID16: ff
I (17528) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive notify value:
E (17528) GATT_SERVER: In ssc_active_callback. writing
E (17528) GATT_SERVER: In write characteristic task. policy is: 0 
I (17528) GATT_CLIENT: aa 28 29 2a 2b 2c 2d 2e 2f 
E (17528) GATT_SERVER: In write characteristic task. policy is: 1627389952 
I (17538) GATT_CLIENT: write descr success
E (17528) GATT_SERVER: In write characteristic task. policy is: 1627389952 
E (17538) GATT_CLIENT: Writing attempt number: 0
E (17548) GATT_CLIENT: Unknown write policy
E (17568) GATT_CLIENT: Unknown write policy
E (17568) GATT_CLIENT: Success writing the char: 0
E (17588) GATT_CLIENT: Conn_id is 0, Gatt_if is 4
I (17608) GATT_CLIENT: write descr success
I (17608) GATT_CLIENT: write char success
I (17648) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive indicate value:
I (17648) GATT_CLIENT: 02 02 02 02 02 02 

Tralasciando un attimo la schifezza che succede sul valore della policy nella scrittura delle caratteristiche.

**Comment by DelVecchioAndrea** [comment]
Sto provando vari esperimenti. Pusho il codice su upper-tier. Purtroppo la comunicazione server-server ancora non funziona. ci sono problemi in fase di connessione e la write_CHR scrive valori completamente randomici. Il meccanismo delle notifiche funziona e riesco a far passare valori ma ancora non possiamo far parlare tra di loro due server.

Server1:

> E (16128) GATT_CLIENT: Found this server at the end of scanning: address:
I (16128) GATT_CLIENT: 24 6f 28 10 7d ae 
E (16128) GATT_CLIENT: type: 0 num_clients: 1 signal strength: 209
E (16138) GATT_CLIENT: Out of the loop: we have collected a device list of: 1 elements
E (16148) GATT_CLIENT: Chosen server in pos: 0
E (16158) BT_APPL: bta_gattc_process_api_open Failed, unknown client_if: 255

Server2:

> E (16249) GATT_CLIENT: Found this server at the end of scanning: address:
I (16259) GATT_CLIENT: 24 6f 28 97 4c 32 
E (16269) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 209
E (16269) GATT_CLIENT: Out of the loop: we have collected a device list of: 1 elements
E (16279) GATT_CLIENT: Chosen server in pos: 0
I (16419) GATT_SERVER: ESP_GATTS_CONNECT_EVT, conn_id = 0
I (16429) GATT_SERVER: 24 6f 28 97 4c 32 
E (16429) GATT_SERVER: Added an entry to the routing table: 
E (16429) GATT_SERVER: Sending routing updates to the neighbour list
E (16439) GATT_SERVER: Preparing to send the update packets to all neighbours
E (16449) GATT_SERVER: Ended updating the neighbours
I (16449) GATT_CLIENT: ESP_GATTC_OPEN_EVT conn_id 0, if 4, status 0, mtu 23
I (16459) GATT_CLIENT: REMOTE MAC:
I (16459) GATT_CLIENT: 24 6f 28 97 4c 32 
W (16469) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16479) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
W (16489) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (16499) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (16629) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (17029) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (17429) GATT_CLIENT: Status 0, MTU 500, conn_id 0
I (17429) GATT_CLIENT: SEARCH RES: conn_id = 0 is primary service 1
I (17429) GATT_CLIENT: start handle 40 end handle 65535 current handle value 40
I (17439) GATT_CLIENT: UUID16: ff
I (17589) GATT_CLIENT: write descr success
I (17629) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive notify value:
E (17629) GATT_SERVER: In ssc_active_callback. writing
E (17629) GATT_SERVER: In write characteristic task. policy is: 0 
I (17629) GATT_CLIENT: aa 28 29 2a 2b 2c 2d 2e 2f 
E (17639) GATT_CLIENT: Writing attempt number: 0
E (17649) GATT_CLIENT: Success writing the char: 0
E (17649) GATT_CLIENT: Conn_id is 0, Gatt_if is 4
I (17669) GATT_CLIENT: write descr success
I (17669) GATT_CLIENT: write char success
I (17709) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive indicate value:
I (17709) GATT_CLIENT: 02 02 02 02 02 02

**Comment by RickyMexx** [comment]
Il comportamento randomico del buffer inviato è dovuto al fatto che sia sullo stack. Infatti questo cambia valore all'interno del task lanciato. Risolto allocando dinamicamente il buffer. Ora funzionano sia la write che la notify nella comunicazione server - server. TODO: aggiungere il delete del buffer all'interno della task in common.

Per ora chiudo la issue. Se ci sono altri problemi la riapriamo.
