### ISSUE TITLE
Problema comunicazione client server

### ISSUE THREAD

**Issue by DelVecchioAndrea** [BE-Mesh/esp32-ble-mesh#26]
Purtroppo riscontro un problema sulla scrittura delle caratteristiche anche per quanto riguarda la comunicazione tra client e server e mi servirebbe una mano per risolverlo altrimenti rischiamo di non avere niente in mano.
Riporto uno dei log dei miei ripetuti esperimenti.
L'errore sembrerebbe essere connesso ad un errore nel gatt_if lato client. 

Riporto i log

Client
> E (21090) GATT_CLIENT: Found this server at the end of scanning: address:
I (21100) GATT_CLIENT: 24 6f 28 97 4c 32 
E (21100) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 187
E (21110) GATT_CLIENT: Out of the loop: we have collected a device list of: 1 elements
E (21120) GATT_CLIENT: Chosen server in pos: 0
E (21120) FUNCTOR: OGGETTO SLAVE SULL'HEAP
I (21130) GATT_CLIENT: 24 6f 28 10 7d ac 
E (21130) GATT_CLIENT: Finished installing all things
E (21140) GATT_CLIENT: I'm about to write something on the server
E (21140) GATT_SERVER: In write characteristic task. policy is: 0 
E (21140) BT_APPL: bta_gattc_process_api_open Failed, unknown client_if: 255
E (21150) GATT_CLIENT: Writing attempt number: 0
E (21160) GATT_CLIENT: Error writing the char: ffffffff
E (21170) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21180) GATT_CLIENT: Writing attempt number: 1
E (21180) GATT_CLIENT: Error writing the char: ffffffff
E (21190) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21190) GATT_CLIENT: Writing attempt number: 2
E (21200) GATT_CLIENT: Error writing the char: ffffffff
E (21200) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21210) GATT_CLIENT: Writing attempt number: 3
E (21210) GATT_CLIENT: Error writing the char: ffffffff
E (21220) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21220) GATT_CLIENT: Writing attempt number: 4
E (21230) GATT_CLIENT: Error writing the char: ffffffff
E (21240) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21240) GATT_CLIENT: Writing attempt number: 5
E (21250) GATT_CLIENT: Error writing the char: ffffffff
E (21250) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21260) GATT_CLIENT: Writing attempt number: 6
E (21260) GATT_CLIENT: Error writing the char: ffffffff
E (21270) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21270) GATT_CLIENT: Writing attempt number: 7
E (21280) GATT_CLIENT: Error writing the char: ffffffff
E (21290) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21290) GATT_CLIENT: Writing attempt number: 8
E (21300) GATT_CLIENT: Error writing the char: ffffffff
E (21300) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21310) GATT_CLIENT: Writing attempt number: 9
E (21310) GATT_CLIENT: Error writing the char: ffffffff
E (21320) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21320) GATT_CLIENT: Writing attempt number: 10
E (21330) GATT_CLIENT: Error writing the char: ffffffff
E (21340) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21340) GATT_CLIENT: Writing attempt number: 11
E (21350) GATT_CLIENT: Error writing the char: ffffffff
E (21350) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21360) GATT_CLIENT: Writing attempt number: 12
E (21360) GATT_CLIENT: Error writing the char: ffffffff
E (21370) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21370) GATT_CLIENT: Writing attempt number: 13
E (21380) GATT_CLIENT: Error writing the char: ffffffff
E (21390) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21390) GATT_CLIENT: Writing attempt number: 14
E (21400) GATT_CLIENT: Error writing the char: ffffffff
E (21400) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21410) GATT_CLIENT: Writing attempt number: 15
E (21410) GATT_CLIENT: Error writing the char: ffffffff
E (21420) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21420) GATT_CLIENT: Writing attempt number: 16
E (21430) GATT_CLIENT: Error writing the char: ffffffff
E (21440) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21440) GATT_CLIENT: Writing attempt number: 17
E (21450) GATT_CLIENT: Error writing the char: ffffffff
E (21450) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21460) GATT_CLIENT: Writing attempt number: 18
E (21460) GATT_CLIENT: Error writing the char: ffffffff
E (21470) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
E (21470) GATT_CLIENT: Writing attempt number: 19
E (21480) GATT_CLIENT: Error writing the char: ffffffff
E (21490) GATT_CLIENT: Conn_id is 0, Gatt_if is 3

Server

> E (7089) GATT_CLIENT: End of scanning!
E (7089) GATT_CLIENT: Out of the loop: we have collected a device list of: 0 elements
E (7089) GATT_CLIENT: REMOVING CLIENT!
E (7099) GATT_CLIENT: I'M A SERVER!!!
I (7099) GATT_SERVER: REGISTER_APP_EVT, status 0, app_id 0
W (7109) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (7119) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (7129) GATT_SERVER: create attribute table successfully, the number handle = 8
I (7129) GATT_SERVER: SERVICE_START_EVT, status 0, service_handle 40
E (7139) FUNCTOR: OGGETTO MASTER SULL'HEAP
E (7139) GATT_SERVER: Finished installing all things
I (7149) GATT_SERVER: 24 6f 28 97 4c 30 

Il server non registra nessuna scrittura purtroppo.

**Comment by Thecave3** [comment]
riesci a linkare la porzione di codice interessata?

**Comment by DelVecchioAndrea** [comment]
Certamente 
In kernel.c

    
    void esp_gap_cb(esp_gap_ble_cb_event_t event, esp_ble_gap_cb_param_t *param){	
    uint8_t *adv_name = NULL;
    uint8_t adv_name_len = 0;
    switch (event) {
    case ESP_GAP_BLE_SCAN_PARAM_SET_COMPLETE_EVT: {
		uint8_t mac[6];
		uint32_t SCAN_DURATION;
		esp_err_t ret = esp_efuse_mac_get_default(mac);
		if (ret) {
            ESP_LOGE(GATTC_TAG, "Cannot retrieve the MAC address, err %x", ret);
            break;
        }
		if(mac[0] == 0) {
			SCAN_DURATION = 1;
		} else {
			SCAN_DURATION = base_scan + mac[5]/scan_dividend;
		}
        ESP_LOGE(GATTC_TAG, "SCAN DURATION IS %d, MAC IS: %d:%d:%d:%d:%d:%d", SCAN_DURATION,
                 mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
        esp_ble_gap_start_scanning(SCAN_DURATION);
		scanning = 1;
        break;
    }
    case ESP_GAP_BLE_SCAN_START_COMPLETE_EVT:
        //scan start complete event to indicate scan start successfully or failed
        if (param->scan_start_cmpl.status != ESP_BT_STATUS_SUCCESS) {
            ESP_LOGE(GATTC_TAG, "scan start failed, error status = %x", param->scan_start_cmpl.status);
            break;
        }
        ESP_LOGI(GATTC_TAG, "scan start success");
		scanning = 1;
        break;
    case ESP_GAP_BLE_SCAN_RESULT_EVT: {
        esp_ble_gap_cb_param_t *scan_result = (esp_ble_gap_cb_param_t *)param;
        switch (scan_result->scan_rst.search_evt) {
        case ESP_GAP_SEARCH_INQ_RES_EVT:
            esp_log_buffer_hex(GATTC_TAG, scan_result->scan_rst.bda, 6); 
            //ESP_LOGI(GATTC_TAG, "searched Adv Data Len %d, Scan Response Len %d", scan_result->scan_rst.adv_data_len, scan_result->scan_rst.scan_rsp_len);
            adv_name = esp_ble_resolve_adv_data(scan_result->scan_rst.ble_adv,
                                                ESP_BLE_AD_TYPE_NAME_CMPL, &adv_name_len);
            //ESP_LOGI(GATTC_TAG, "searched Device Name Len %d", adv_name_len);
            esp_log_buffer_char(GATTC_TAG, adv_name, adv_name_len);
    #if CONFIG_EXAMPLE_DUMP_ADV_DATA_AND_SCAN_RESP
            if (scan_result->scan_rst.adv_data_len > 0) {
                ESP_LOGI(GATTC_TAG, "adv data:");
                esp_log_buffer_hex(GATTC_TAG, &scan_result->scan_rst.ble_adv[0], scan_result->scan_rst.adv_data_len);
            }
            if (scan_result->scan_rst.scan_rsp_len > 0) {
                ESP_LOGI(GATTC_TAG, "scan resp:");
                esp_log_buffer_hex(GATTC_TAG, &scan_result->scan_rst.ble_adv[scan_result->scan_rst.adv_data_len], scan_result->scan_rst.scan_rsp_len);
            }
    #endif
            ESP_LOGI(GATTC_TAG, "\n");
            if (adv_name != NULL) {
				//adv_name_len = DEVICE_NAME_LEN;
                if (strlen(remote_device_name) == DEVICE_NAME_LEN && strncmp((char *)adv_name,     remote_device_name, DEVICE_NAME_LEN) == 0) {
					/*
					int c = adv_name[CLIENTS_IDX] - '0';
					if(c > CLIENTS_NUMBER_LIMIT) {
						// The number of clients is over the limit
						ESP_LOGE(GATTC_TAG, "Too many clients here!");
						break;
					}		
                    ESP_LOGI(GATTC_TAG, "searched device %s\n", remote_device_name);
                    if (connect == false) {
                        connect = true;
                        ESP_LOGI(GATTC_TAG, "connect to the remote device.");
                        esp_ble_gap_stop_scanning();
                        esp_ble_gattc_open(gl_profile_tab2[PROFILE_A_APP_ID].gattc_if, scan_result->scan_rst.bda, scan_result->scan_rst.ble_addr_type, true);
                    }
					*/
					processDevice(scan_result, adv_name, adv_name_len);
                }
            }
            break;
        case ESP_GAP_SEARCH_INQ_CMPL_EVT:
			//ESP_LOGE(GATTC_TAG, "I didn't find a server! I'm going to be a server...");
			ESP_LOGE(GATTC_TAG, "End of scanning!");
			(*endscanning_cb)(scan_res, scan_seq,CLIENT_SERVER); //QUESTA CALLBACK!
			scan_seq = 0;
			//unregister_client();
			//gatt_server_main();		
            break;
        default:
            break;
        }
        break;
    }
    case ESP_GAP_BLE_SCAN_STOP_COMPLETE_EVT:
        if (param->scan_stop_cmpl.status != ESP_BT_STATUS_SUCCESS){
            ESP_LOGE(GATTC_TAG, "scan stop failed, error status = %x", param->scan_stop_cmpl.status);
            break;
        }
        ESP_LOGI(GATTC_TAG, "stop scan successfully");
		scanning = 0;
        break;
    case ESP_GAP_BLE_ADV_STOP_COMPLETE_EVT:
        if (param->adv_stop_cmpl.status != ESP_BT_STATUS_SUCCESS){
            ESP_LOGE(GATTC_TAG, "adv stop failed, error status = %x", param->adv_stop_cmpl.status);
            break;
        }
        ESP_LOGI(GATTC_TAG, "stop adv successfully");
        break;
    case ESP_GAP_BLE_UPDATE_CONN_PARAMS_EVT:
         ESP_LOGI(GATTC_TAG, "update connection params status = %d, min_int = %d, max_int = %d,conn_int = %d,latency = %d, timeout = %d",
                  param->update_conn_params.status,
                  param->update_conn_params.min_int,
                  param->update_conn_params.max_int,
                  param->update_conn_params.conn_int,
                  param->update_conn_params.latency,
                  param->update_conn_params.timeout);
        break;
    default:
        break;
    }
    }

endscanning_cb è la callback che viene invocata alla fine dello scanning e che sceglie il dispositivo a cui connettersi.

Questa callback chiama questa funzione in callbacks.cpp

    void Callback::endscanning_callback(device* device_list,uint8_t count,uint8_t type){
        int i;
        

        //We perform some integrity check.
        if(device_list == NULL)
            return;

        if(count > SCAN_LIMIT){
            ESP_LOGE(GATTC_TAG,"Error in endscanning_callback. Device number: %d exceed the SCAN_LIMIT: %d",
                                count,SCAN_LIMIT);
            return;
        }

        for(i = 0; i<count; i++){
            
            uint8_t* addr = device_list[i].mac;
            uint8_t type = device_list[i].addr_type;
            uint8_t num_clients = device_list[i].clients_num;
            uint8_t signal_strength = device_list[i].rssi;
            ESP_LOGE(GATTC_TAG,"Found this server at the end of scanning: address:");
            esp_log_buffer_hex(GATTC_TAG,addr, MAC_ADDRESS_SIZE);
            ESP_LOGE(GATTC_TAG,"type: %d num_clients: %d signal strength: %d",type,num_clients,signal_strength);
        
        }
        ESP_LOGE(GATTC_TAG, "Out of the loop: we have collected a device list of: %d elements",count);
        connection_policy_t policy = Maximum_rssi_value_policy;
        if (count == 0){
            //If no server is found we become a server ourselves
            becomeServer();
            //ESP_LOGE(GATTC_TAG,"I become a server");
            return;
        }
        else{
            int server_pos = connect_to_server(device_list,count,policy);
            if(server_pos == -1){
                ESP_LOGE(GATTC_TAG, "Unable to connect to any server");
                return;
            }
            else{
                ESP_LOGE(GATTC_TAG,"Chosen server in pos: %d",server_pos);
                if(type == CLIENT_SERVER){
                    //We initialize client object if it is a client_server connection.
                    init_callback(CLIENT);
                }
                else if(type == SERVER_SERVER){
                    
                }
                return;
            }
        }
    }

Riporto tutte le funzioini invocate da endscanning_callback, definite solo in callbacks.cpp

    int Callback::connect_to_server(device* device_list, int device_list_size,connection_policy_t policy){
        bool all_discarded = check_all_discarded();
        //ESP_LOGE(GATTC_TAG,"I checked");
        if(all_discarded)
            return -1;
        else{
            int server_pos = choose_server(device_list,device_list_size,policy);
            uint8_t connection_ret = connectTo(device_list[server_pos],device_list[server_pos].clients_num);
            if(connection_ret){
                discarded[server_pos] = true;
                //We recursively look for another server keeping track of the discarded one.
                int conn_ret = connect_to_server(device_list,device_list_size,policy);
                return conn_ret;
            }
            else{
                reset_discarded();
                return 0;
            }
        }
    }

    //Choose a server to connect to according to the policy "policy"
    

    int Callback::choose_server(device* device_list,int device_list_size,connection_policy_t policy){
        
        //Check if the buffer exists.
        if(device_list == NULL)
            return -1;

        //Error: illegal device list size.
        if(device_list_size > SCAN_LIMIT)
            return -1;
        
        //Then choose the server according to the policy.
        switch(policy){
            case Minimum_rssi_value_policy: {
                int i;
                uint8_t rssi_min = device_list[0].rssi;
                int server_pos = 0; 
                for( i = 1; i< device_list_size; i++){
                    if(discarded[i] == false){
                        if(device_list[i].rssi < rssi_min){
                            rssi_min = device_list[i].rssi;
                            server_pos = i;
                        }
                    }
                }
                return server_pos;
            }
            case Maximum_rssi_value_policy:{
                int i;
                uint8_t rssi_max = device_list[0].rssi;
                int server_pos = 0;
                for(i = 0; i< device_list_size; ++i){
                    if(discarded[i] == false){
                        if(device_list[i].rssi > rssi_max){
                            rssi_max = device_list[i].rssi;
                            server_pos = i;
                        }
                    }
                }
                return server_pos;
            }
            case Random_policy:{
                break;
            }
            case Fcfs_policy:{
                break;
            }
            default:{
                ESP_LOGE(GATTC_TAG, "Unknown policy value in choosing the server");
                break;
            }
        }
        return -1;
    }

**Comment by RickyMexx** [comment]
Bug fixato. Problema di minore importanza da fixare per il secondo argomento della connectTo chiamata in callback.cpp line 232. Ora la funzione connectTo ha gli if impostati correttamente e un nuovo flag per le connessioni degli internal_client. Il secondo problema era relativo al passaggio di strutture in stack (slave.cpp, write_characteristic) a molteplici task -> risolto allocando dinamicante.
