### ISSUE TITLE
Bug nelle notifiche sulle caratteristiche e su get_server_connids

### ISSUE THREAD

**Issue by DelVecchioAndrea** [BE-Mesh/esp32-ble-mesh#30]
Segnalo un bug nel processo di notifica sulle caratteristiche. Il server non riesce a notificare sulle caratteristiche IDX_CHAR_VAL_B e IDX_CHAR_VAL_C.

Riporto ora i log di client e server e le parti di codice interessate.

> E (7090) GATT_CLIENT: REMOVING CLIENT!
E (7100) GATT_CLIENT: I'M A SERVER!!!
I (7110) GATT_SERVER: REGISTER_APP_EVT, status 0, app_id 0
W (7110) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (7120) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (7130) GATT_SERVER: create attribute table successfully, the number handle = 8
I (7140) GATT_SERVER: SERVICE_START_EVT, status 0, service_handle 40
E (7140) FUNCTOR: OGGETTO MASTER SULL'HEAP
E (7140) GATT_SERVER: Finished installing all things
I (20760) GATT_SERVER: ESP_GATTS_CONNECT_EVT, conn_id = 0
I (20770) GATT_SERVER: 24 6f 28 10 7d ae 
E (20770) GATT_SERVER: Added an entry to the routing table: 
E (20770) GATT_SERVER: Sending routing updates to the neighbour list
E (20780) GATT_SERVER: Preparing to send the update packets to all neighbours
E (20790) GATT_SERVER: Ended updating the neighbours
W (20800) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (20800) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (20970) GATT_SERVER: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (21770) GATT_SERVER: ESP_GATTS_MTU_EVT, MTU 500
I (21930) GATT_SERVER: GATT_WRITE_EVT, handle = 43, value len = 2, value :
I (21930) GATT_SERVER: 01 00 
I (21930) GATT_SERVER: notify enable
I (21940) GATT_SERVER: ESP_GATTS_CONF_EVT, status = 0, attr_handle 42
I (22090) GATT_SERVER: GATT_WRITE_EVT, handle = 42, value len = 18, value :
I (22090) GATT_SERVER: 12 00 00 00 04 24 6f 28 10 7d ac 24 6f 28 97 4c 
I (22090) GATT_SERVER: 32 04 
Received a packet
I (22100) FUNCTOR: 12 00 00 00 04 24 6f 28 10 7d ac 24 6f 28 97 4c 
I (22110) FUNCTOR: 32 04 
msg size: 18
E (22110) GATT_SERVER: In Master::parse_message_receive. Expected to read: 18 bytes but 22 actually read
Ho un totale di m_rx_entries: 1[unserialize] received id no. 04
E (22130) GATT_SERVER: In ping reception callback
E (22130) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (22140) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (22150) GATT_SERVER: Pinging client: 0 
E (22150) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (22160) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (22170) GATT_SERVER: In send notification conn_id: 0 characteristic: 7
E (22180) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (22190) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (22190) GATT_SERVER: Pinging client: 1 
E (22200) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (22210) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (22220) GATT_SERVER: In send notification conn_id: 1 characteristic: 7
E (22220) GATT_SERVER: In ping transmission callback: Error in notifying the client: 1 on the characteristic: 7
E (22230) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (22240) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (22250) GATT_SERVER: Pinging client: 2 
E (22250) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (22260) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (22270) GATT_SERVER: In send notification conn_id: 2 characteristic: 7
E (22280) GATT_SERVER: In ping transmission callback: Error in notifying the client: 2 on the characteristic: 7
E (22290) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (22300) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (22310) GATT_SERVER: Pinging client: 3 
E (22310) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (22320) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (22330) GATT_SERVER: In send notification conn_id: 3 characteristic: 7
E (22330) GATT_SERVER: In ping transmission callback: Error in notifying the client: 3 on the characteristic: 7
E (22350) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (22350) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (22360) GATT_SERVER: Pinging client: 4 
E (22370) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (22380) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (22380) GATT_SERVER: In send notification conn_id: 4 characteristic: 7
E (22390) GATT_SERVER: In ping transmission callback: Error in notifying the client: 4 on the characteristic: 7
E (22400) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (22410) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (22420) GATT_SERVER: Pinging client: 5 
E (22420) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (22430) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (22440) GATT_SERVER: In send notification conn_id: 5 characteristic: 7
E (22450) GATT_SERVER: In ping transmission callback: Error in notifying the client: 5 on the characteristic: 7
E (22460) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (22470) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (22470) GATT_SERVER: Pinging client: 6 
E (22480) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (22490) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (22500) GATT_SERVER: In send notification conn_id: 6 characteristic: 7
E (22500) GATT_SERVER: In ping transmission callback: Error in notifying the client: 6 on the characteristic: 7
I (22570) GATT_SERVER: ESP_GATTS_CONF_EVT, status = 0, attr_handle 47

E di client

> E (20590) GATT_CLIENT: End of scanning!
E (20600) GATT_CLIENT: Found this server at the end of scanning: address:
I (20610) GATT_CLIENT: 24 6f 28 97 4c 32 
E (20610) GATT_CLIENT: type: 0 num_clients: 0 signal strength: 192
E (20620) GATT_CLIENT: Out of the loop: we have collected a device list of: 1 elements
E (20630) GATT_CLIENT: Chosen server in pos: 0
I (20780) GATT_CLIENT: ESP_GATTC_CONNECT_EVT conn_id 0, if 3
I (20780) GATT_CLIENT: REMOTE MAC:
I (20780) GATT_CLIENT: 24 6f 28 97 4c 32 
I (20790) GATT_CLIENT: open success
I (20970) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (21810) GATT_CLIENT: ESP_GATTC_CFG_MTU_EVT, Status 0, MTU 500, conn_id 0
I (21810) GATT_CLIENT: SEARCH RES: conn_id = 0 is primary service 1
I (21820) GATT_CLIENT: start handle 40 end handle 65535 current handle value 40
I (21820) GATT_CLIENT: service found
I (21830) GATT_CLIENT: UUID16: ff
I (21830) GATT_CLIENT: Get service information from remote device
I (21840) GATT_CLIENT: ESP_GATTC_SEARCH_CMPL_EVT
I (21850) GATT_CLIENT: ESP_GATTC_REG_FOR_NOTIFY_EVT
I (21970) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive notify value:
I (21970) GATT_CLIENT: aa 28 29 2a 2b 2c 2d 2e 2f 
I (21970) GATT_CLIENT: write descr success 
E (21980) FUNCTOR: OGGETTO SLAVE SULL'HEAP
I (21980) GATT_CLIENT: 24 6f 28 10 7d ac 
E (21990) GATT_CLIENT: Finished installing all things
E (21990) GATT_CLIENT: I'm about to write something on the server
E (22000) GATT_CLIENT: TEST IN THE SLAVE: conn_id 0, gatt_if 3
E (22010) GATT_CLIENT: In ping transmission callback: we begin to retrieve the arguments
E (22020) GATT_CLIENT: In ping transmission callback: we ended to retrieve the arguments
E (22030) GATT_CLIENT: BUFFER THAT TASK IS GOING TO WRITE IS:
I (22030) GATT_CLIENT: 12 00 00 00 04 24 6f 28 10 7d ac 24 6f 28 97 4c 
I (22040) GATT_CLIENT: 32 04 
E (22040) GATT_SERVER: In write characteristic task. policy is: 0 
E (22050) GATT_CLIENT: Writing attempt number: 0
E (22050) GATT_CLIENT: Success writing the char: 0
E (22060) GATT_CLIENT: Conn_id is 0, Gatt_if is 3

Nessun evento di notifica è stato registrato lato client.

Le porzioni di codice interessate sono:
In master.cpp , questa funzione si occupa di trasmettere il pacchetto ROUTING_PING_ID come pong

    void Master::ping_transmission_callback(uint8_t* buffer,uint8_t size, MessageHeader* header_t,
                                    void* args)
    {
        ESP_LOGE(GATTS_TAG,"In ping transmission callback: beginning to parse all arguments");

        uint16_t * ptr = (uint16_t*) args;
        uint16_t gatt_if = *ptr;
        uint8_t* _ptr = (uint8_t*)(ptr + sizeof(uint16_t));
        uint8_t conn_id = *_ptr;
        _ptr = (uint8_t*)(_ptr + sizeof(uint8_t));
        uint8_t server_id = *_ptr;
        _ptr = (uint8_t*)(_ptr + sizeof(uint8_t));
        uint8_t notify = *_ptr;

        ESP_LOGE(GATTS_TAG,"In ping transmission callback: ended to parse all arguments");

        uint8_t characteristic = IDX_CHAR_VAL_C;

        if(notify == NOTIFY_NO){
            write_policy_t policy = Standard;
            ErrStatus write_ret = write_characteristic(characteristic,buffer,size,gatt_if,conn_id,
                                                        policy);
            if(write_ret != Success){
                ESP_LOGE(GATTS_TAG,"In ping transmission callback: Error in writing the characteristic: %d",characteristic);
            }
        }
        else{
            uint8_t notification_ret = send_notification(conn_id,characteristic,buffer,size);
                                                    
            if(notification_ret){
                ESP_LOGE(GATTS_TAG,"In ping transmission callback: Error in notifying the client: %d on the characteristic: %d",conn_id,characteristic);
            }
        }

        return;
    }

Per quanto riguarda la comunicazione tra server e client notify è impostato come NOTIFY_NO quindi viene invocata

    uint8_t Master::send_notification(uint8_t conn_id,uint8_t characteristic,uint8_t* data,
                                    uint8_t data_size)
    {
        ESP_LOGE(GATTS_TAG,"In send notification conn_id: %d characteristic: %d",
                            conn_id, characteristic);
        uint8_t notification_ret = notify_client(conn_id,characteristic,data,data_size);
        return notification_ret;
    }

}

In kernel.c notify_client è

    uint8_t notify_client(uint8_t conn_id, uint8_t chr, uint8_t* data, uint8_t data_size) {
	esp_err_t ret;
	
	ret= esp_ble_gatts_send_indicate(gl_profile_tab[PROFILE_A_APP_ID].gatts_if, conn_id, char_handle_table[chr], data_size, data, true);
	if(ret != ESP_OK) {
		return 1;
	}
	return 0;
}

Una volta ricevuta la notifica viene triggerata la callback "ntf_cb"

    case ESP_GATTC_NOTIFY_EVT: {
		esp_err_t ret;
        if (p_data->notify.is_notify){
            ESP_LOGI(GATTC_TAG, "ESP_GATTC_NOTIFY_EVT, receive notify value:");
           
        }else{
            ESP_LOGI(GATTC_TAG, "ESP_GATTC_NOTIFY_EVT, receive indicate value:");
            (*ntf_cb)(gattc_if,get_client_connid(),p_data->notify.value[1]);
        }
        if(p_data->notify.value[0] == 0xaa) {
			// Handles for characteristics
			if(p_data->notify.value_len == HRS_IDX_NB+1) {
				int i;
				for(i=1; i<p_data->notify.value_len; i++) {
					CHR_HANDLES[i-1] = p_data->notify.value[i];
				}
			}
			
ntf_cb è un puntatore a funzione definito in callbacks.cpp

    void Callback::notify_callback(uint16_t gatt_if,uint8_t conn_id,uint8_t characteristic){
        //Triggered when a client is notified. The client can now read the characteristic
        
        if(characteristic == IDX_CHAR_VAL_A || characteristic == IDX_CHAR_VAL_B || characteristic == IDX_CHAR_VAL_C){
            ESP_LOGE(FUNCTOR_TAG,"In notify callback. Notify registered to a well known characteristic: %d",characteristic);
        }
        else{
            ESP_LOGE(FUNCTOR_TAG,"In notify callback: I don't know this characteristic: %d",characteristic);
        }

        if (slave_instance){  
            ESP_LOGE(FUNCTOR_TAG,"In notify callback. Attempting to read the characteristic");  
        
            uint8_t* received_bytes =  slave_instance->read_characteristic(characteristic,gatt_if, conn_id);
            if( received_bytes == NULL)
                return;
            
            //esp_log_buffer_hex(FUNCTOR_TAG,received_bytes,6);
            //Check if read is complete.
            //parse the message
            ESP_LOGE(FUNCTOR_TAG,"In notify callback. Attempting to read the message with the message handler");
            std::size_t  ret = slave_instance->get_message_handler()->read(received_bytes);
            if(ret){
                ESP_LOGE(FUNCTOR_TAG,"In notify callback: read: %d  bytes",ret);
                esp_log_buffer_hex(FUNCTOR_TAG,received_bytes,ret);
            }
            ESP_LOGE(FUNCTOR_TAG,"In notify callback. Handling the message with the message handler");
            slave_instance->get_message_handler()->handle();
        }

    }

La notifica su IDX_CHAR_VAL_A avviene correttamente. Quando vado a leggere la caratteristica però c'è un errore di indicizzazione. In altre parole _read_characteristic_ viene invocata su  IDX_SVC (cioè 0) e non su IDX_CHAR_VAL_A che è 2.

Riporto i log di server e client

Server

> E (7099) GATT_CLIENT: REMOVING CLIENT!
E (7109) GATT_CLIENT: I'M A SERVER!!!
I (7109) GATT_SERVER: REGISTER_APP_EVT, status 0, app_id 0
W (7119) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (7129) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (7139) GATT_SERVER: create attribute table successfully, the number handle = 8
I (7139) GATT_SERVER: SERVICE_START_EVT, status 0, service_handle 40
E (7149) FUNCTOR: OGGETTO MASTER SULL'HEAP
E (7149) GATT_SERVER: Finished installing all things
I (18189) GATT_SERVER: ESP_GATTS_CONNECT_EVT, conn_id = 0
I (18189) GATT_SERVER: 24 6f 28 10 7d ae 
E (18189) GATT_SERVER: Added an entry to the routing table: 
E (18189) GATT_SERVER: Sending routing updates to the neighbour list
E (18199) GATT_SERVER: Preparing to send the update packets to all neighbours
E (18209) GATT_SERVER: Ended updating the neighbours
W (18219) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
W (18219) BT_BTM: BTM_BleWriteScanRsp, Partial data write into ADV
I (18389) GATT_SERVER: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (19189) GATT_SERVER: ESP_GATTS_MTU_EVT, MTU 500
I (19349) GATT_SERVER: GATT_WRITE_EVT, handle = 43, value len = 2, value :
I (19349) GATT_SERVER: 01 00 
I (19349) GATT_SERVER: notify enable
I (19359) GATT_SERVER: ESP_GATTS_CONF_EVT, status = 0, attr_handle 42
I (19509) GATT_SERVER: GATT_WRITE_EVT, handle = 42, value len = 18, value :
I (19509) GATT_SERVER: 12 00 00 00 04 24 6f 28 10 7d ac 24 6f 28 97 4c 
I (19519) GATT_SERVER: 32 04 
Received a packet
I (19519) FUNCTOR: 12 00 00 00 04 24 6f 28 10 7d ac 24 6f 28 97 4c 
I (19529) FUNCTOR: 32 04 
msg size: 18
E (19529) GATT_SERVER: In Master::parse_message_receive. Expected to read: 18 bytes but 22 actually read
Ho un totale di m_rx_entries: 1[unserialize] received id no. 04
E (19549) GATT_SERVER: In ping reception callback
E (19549) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (19559) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (19569) GATT_SERVER: Pinging client: 0 
E (19579) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (19589) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (19589) GATT_SERVER: In send notification conn_id: 0 characteristic: 2
E (19599) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (19609) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (19619) GATT_SERVER: Pinging client: 1 
E (19619) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (19629) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (19639) GATT_SERVER: In send notification conn_id: 1 characteristic: 2
E (19639) GATT_SERVER: In ping transmission callback: Error in notifying the client: 1 on the characteristic: 2
E (19659) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (19669) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (19669) GATT_SERVER: Pinging client: 2 
E (19679) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (19689) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (19689) GATT_SERVER: In send notification conn_id: 2 characteristic: 2
E (19699) GATT_SERVER: In ping transmission callback: Error in notifying the client: 2 on the characteristic: 2
E (19709) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (19719) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (19729) GATT_SERVER: Pinging client: 3 
E (19729) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (19739) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (19749) GATT_SERVER: In send notification conn_id: 3 characteristic: 2
E (19759) GATT_SERVER: In ping transmission callback: Error in notifying the client: 3 on the characteristic: 2
E (19769) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (19779) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (19779) GATT_SERVER: Pinging client: 4 
E (19789) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (19799) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (19809) GATT_SERVER: In send notification conn_id: 4 characteristic: 2
E (19809) GATT_SERVER: In ping transmission callback: Error in notifying the client: 4 on the characteristic: 2
E (19819) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (19829) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (19839) GATT_SERVER: Pinging client: 5 
E (19839) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (19849) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (19859) GATT_SERVER: In send notification conn_id: 5 characteristic: 2
E (19869) GATT_SERVER: In ping transmission callback: Error in notifying the client: 5 on the characteristic: 2
E (19879) GATT_SERVER: In ping reception callback: beginning to parse all arguments
E (19889) GATT_SERVER: In ping reception callback: ended to parse all arguments
E (19899) GATT_SERVER: Pinging client: 6 
E (19899) GATT_SERVER: In ping transmission callback: beginning to parse all arguments
E (19909) GATT_SERVER: In ping transmission callback: ended to parse all arguments
E (19919) GATT_SERVER: In send notification conn_id: 6 characteristic: 2
E (19919) GATT_SERVER: In ping transmission callback: Error in notifying the client: 6 on the characteristic: 2
I (19989) GATT_SERVER: ESP_GATTS_CONF_EVT, status = 0, attr_handle 42

Client

> E (20380) GATT_CLIENT: Chosen server in pos: 0
I (20600) GATT_CLIENT: ESP_GATTC_CONNECT_EVT conn_id 0, if 3
I (20600) GATT_CLIENT: REMOTE MAC:
I (20600) GATT_CLIENT: 24 6f 28 97 4c 32 
I (20600) GATT_CLIENT: open success
I (20780) GATT_CLIENT: update connection params status = 0, min_int = 16, max_int = 32,conn_int = 32,latency = 0, timeout = 400
I (21630) GATT_CLIENT: ESP_GATTC_CFG_MTU_EVT, Status 0, MTU 500, conn_id 0
I (21630) GATT_CLIENT: SEARCH RES: conn_id = 0 is primary service 1
I (21630) GATT_CLIENT: start handle 40 end handle 65535 current handle value 40
I (21640) GATT_CLIENT: service found
I (21640) GATT_CLIENT: UUID16: ff
I (21650) GATT_CLIENT: Get service information from remote device
I (21650) GATT_CLIENT: ESP_GATTC_SEARCH_CMPL_EVT
I (21660) GATT_CLIENT: ESP_GATTC_REG_FOR_NOTIFY_EVT
I (21790) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive notify value:
I (21790) GATT_CLIENT: aa 28 29 2a 2b 2c 2d 2e 2f 
I (21790) GATT_CLIENT: write descr success 
E (21790) FUNCTOR: OGGETTO SLAVE SULL'HEAP
I (21800) GATT_CLIENT: 24 6f 28 10 7d ac 
E (21800) GATT_CLIENT: Finished installing all things
E (21810) GATT_CLIENT: I'm about to write something on the server
E (21820) GATT_CLIENT: TEST IN THE SLAVE: conn_id 0, gatt_if 3
E (21820) GATT_CLIENT: In ping transmission callback: we begin to retrieve the arguments
E (21830) GATT_CLIENT: In ping transmission callback: we ended to retrieve the arguments
E (21840) GATT_CLIENT: BUFFER THAT TASK IS GOING TO WRITE IS:
I (21850) GATT_CLIENT: 12 00 00 00 04 24 6f 28 10 7d ac 24 6f 28 97 4c 
I (21850) GATT_CLIENT: 32 04 
E (21860) GATT_SERVER: In write characteristic task. policy is: 0 
E (21860) GATT_CLIENT: Writing attempt number: 0
E (21870) GATT_CLIENT: Success writing the char: 0
E (21870) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
I (22350) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive indicate value:
E (22350) FUNCTOR: In notify callback: I don't know this characteristic: 0
E (22350) FUNCTOR: In notify callback. Attempting to read the characteristic
I (22360) GATT_CLIENT: 12 00 00 00 04 24 6f 28 10 7d ae 00 00 00 00 00 
I (22370) GATT_CLIENT: 00 04 

C'è un altro problema nella funzione get_server_connids definita in kernel.c

     uint8_t* get_server_connids() {
	int i;
	uint8_t* arr = malloc(sizeof(uint8_t)*TOTAL_NUMBER_LIMIT);
	for(i=0; i<TOTAL_NUMBER_LIMIT; i++) {
		if(ID_TABLE[i] != NOID) arr[i] = 1;
		else arr[i] = 0;
	}
	return arr;
    }

La struttura ritornata "arr" presenta valori diversi da 0 anche per conn_id non assegnati.
Infatti in:

    void Master::ping_reception_callback(MessageHeader* header_t,void * args){
        ESP_LOGE(GATTS_TAG,"In ping reception callback");
        //Notify to all clients of the ping message.
        

        uint8_t pong_flag;
        RoutingPingMessage* rt_ping_message = (RoutingPingMessage*)header_t;
        if(rt_ping_message->pong_flag() == PONG_FLAG_VALUE)
            pong_flag = PONG_FLAG_VALUE;
        else
            pong_flag = PING_FLAG_VALUE;
        uint8_t * server_connids = get_server_connids();
        int i;
        for(i = 0; i<TOTAL_NUMBER_LIMIT; ++i){
            if(server_connids[i] == 1){ //QUESTA RIGA!!
                if(get_type_connection(i) == CLIENT){
                    uint8_t * client_address = get_connid_MAC(i);
                    dev_addr_t cl_addr = _build_dev_addr(client_address);
                    RoutingPingMessage client_ping_message(cl_addr,rt_ping_message->source(),pong_flag);
                    uint8_t notify = NOTIFY_YES;

                    ESP_LOGE(GATTS_TAG,"In ping reception callback: beginning to parse all arguments");

                    uint16_t* ptr = (uint16_t*) args;
                    *ptr = 0;
                    uint8_t* _ptr = (uint8_t*) (ptr + sizeof(uint16_t));
                    *_ptr = i;
                    _ptr = (uint8_t*)(_ptr + sizeof(uint8_t));
                    *_ptr = 0;
                    _ptr = (uint8_t*)(_ptr + sizeof(uint8_t*));
                    *_ptr = notify;

                    ESP_LOGE(GATTS_TAG,"In ping reception callback: ended to parse all arguments");

                    ESP_LOGE(GATTS_TAG,"Pinging client: %d ",i);

                    ErrStatus write_ret = mes_handler.send((MessageHeader*)&client_ping_message);
                    if(write_ret != Success){
                        ESP_LOGE(GATTS_TAG,"Error in sending the message to notify the client: %d ",i);
                    }
                    else{
                        mes_handler.handle();
                    }

                    }
                }
         }
        

        //Ping all neighbour servers
        for(auto it = neighbours.begin(); it != neighbours.end(); ++it){
            connected_server_params_t server = *it;
            uint16_t  gatt_if = server.gatt_if;
            uint8_t conn_id = server.conn_id;
            uint8_t server_id = server.server_id;
            uint8_t notify = NOTIFY_NO;

            dev_addr_t dest_addr = server.server_mac_address;

            RoutingPingMessage new_routing_ping_message(dest_addr,rt_ping_message->source(),pong_flag);

            ESP_LOGE(GATTS_TAG,"In ping reception callback: beginning to parse all arguments");

            uint16_t* ptr = (uint16_t*) args;
            *ptr = gatt_if;
            uint8_t* _ptr = (uint8_t*) (ptr + sizeof(uint16_t));
            *_ptr = conn_id;
            _ptr = (uint8_t*)(_ptr + sizeof(uint8_t));
            *_ptr = server_id;
            _ptr = (uint8_t*)(_ptr + sizeof(uint8_t*));
            *_ptr = notify;

            ESP_LOGE(GATTS_TAG,"In ping reception callback: ended to parse all arguments");
            
            ESP_LOGE(GATTS_TAG, "Sending ping to the neighbour: ");
            uint8_t _addr[MAC_ADDRESS_SIZE];
            int i;
            for(i =0; i<MAC_ADDRESS_SIZE; i++){
                _addr[i] = dest_addr[i];
            }
            esp_log_buffer_hex(GATTS_TAG,_addr,MAC_ADDRESS_SIZE);
            if(server_id == SERVER_S1 || server_id == SERVER_S2 || server_id == SERVER_S3){
                ErrStatus status = mes_handler.send((MessageHeader*)&new_routing_ping_message);
                if(status != Success){
                    ESP_LOGE(GATTS_TAG,"Error in sending ping to server: %d",server_id);
                    esp_log_buffer_hex(GATTS_TAG,_addr,MAC_ADDRESS_SIZE);
                }
                else{
                    mes_handler.handle();
                }
            }

        }
        
        
        

        return;
    }

Il test **if(server_connids[i] == 1)** ha successo anche per conn_id non assegnati.

Dovremmo anche trovare un modo per gestire la liberazione di "arr", l'array costruito da notify_client in modo da evitare sprechi inutili di memoria.

**Comment by RickyMexx** [comment]
Bug dei connection id risolto in 383df77d56467a67a5f551662d81db659a75b0e7.
