### ISSUE TITLE
Bug in MessageHandler::read

### ISSUE THREAD

**Issue by DelVecchioAndrea** [BE-Mesh/esp32-ble-mesh#31]
Sto continuando a lavorare sulla parte del flooding e sto osservando un comportamento anomalo del message_handler in ricezione: non riesco ad estrapolare il campo **source**

Qualsiasi sia il valore che passo al costruttore del messaggio, in ricezione leggo 6 byte di zeri. Sapere chi manda un pacchetto ROUTING_PING_ID è fondamentale per come intendo affrontare la questione.
Riporto i log del client e del server e il codice di interesse

>I (20739) GATT_SERVER: ESP_GATTS_CONF_EVT, status = 0, attr_handle 42
I (20819) GATT_SERVER: GATT_WRITE_EVT, handle = 42, value len = 18, value :
I (20819) GATT_SERVER: 12 00 00 00 04 24 6f 28 97 4c 32 24 6f 28 10 91 
I (20819) GATT_SERVER: 8c 04 
Received a packet
I (20829) FUNCTOR: 12 00 00 00 04 24 6f 28 97 4c 32 24 6f 28 10 91 
I (20839) FUNCTOR: 8c 04 
msg size: 18
E (20839) GATT_SERVER: In Master::parse_message_receive. Expected to read: 18 bytes but 22 actually read
Ho un totale di m_rx_entries: 1[unserialize] received id no. 04
E (20859) GATT_SERVER: In ping reception callback: dest_address is
I (20859) GATT_SERVER: 24 6f 28 10 91 8c 
E (20869) GATT_SERVER: In ping reception callback: src_address is
I (20869) GATT_SERVER: 00 00 00 00 00 00 
E (20879) GATT_SERVER: Pinging client: 0 
E (20879) GATT_SERVER: In send notification conn_id: 0 characteristic: 2
E (20889) GATT_SERVER: Pinging client: 1 
E (20899) GATT_SERVER: In send notification conn_id: 1 characteristic: 2
E (20899) GATT_SERVER: In ping transmission callback: Error in notifying the client: 1 on the characteristic: 2
E (20909) GATT_SERVER: Pinging client: 2 
E (20919) GATT_SERVER: In send notification conn_id: 2 characteristic: 2
E (20929) GATT_SERVER: In ping transmission callback: Error in notifying the client: 2 on the characteristic: 2
E (20939) GATT_SERVER: Pinging client: 3 
E (20939) GATT_SERVER: In send notification conn_id: 3 characteristic: 2
E (20949) GATT_SERVER: In ping transmission callback: Error in notifying the client: 3 on the characteristic: 2
E (20959) GATT_SERVER: Pinging client: 4 
E (20959) GATT_SERVER: In send notification conn_id: 4 characteristic: 2
E (20969) GATT_SERVER: In ping transmission callback: Error in notifying the client: 4 on the characteristic: 2
E (20979) GATT_SERVER: Pinging client: 5 
E (20989) GATT_SERVER: In send notification conn_id: 5 characteristic: 2
E (20989) GATT_SERVER: In ping transmission callback: Error in notifying the client: 5 on the characteristic: 2
E (21009) GATT_SERVER: Pinging client: 6 
E (21009) GATT_SERVER: In send notification conn_id: 6 characteristic: 2
E (21019) GATT_SERVER: In ping transmission callback: Error in notifying the client: 6 on the characteristic: 2

Gli errori sulla notifica delle caratteristiche sono dovuti ad un altro bug di un'altra issue ma non credo siano determinanti.

Client

>  E (44049) GATT_SERVER: In write characteristic task. policy is: 0 
I (44049) GATT_CLIENT: 12 00 00 00 04 24 6f 28 10 91 8e 00 00 00 00 00 
E (44059) GATT_CLIENT: Writing attempt number: 0
I (44059) GATT_CLIENT: 00 04 
E (44069) GATT_CLIENT: Success writing the char: 0
E (44079) GATT_CLIENT: Conn_id is 0, Gatt_if is 3
I (44349) GATT_CLIENT: ESP_GATTC_NOTIFY_EVT, receive indicate value:
E (44349) FUNCTOR: In notify callback: I don't know this characteristic: 0
E (44349) FUNCTOR: In notify callback. Attempting to read the characteristic
I (44359) FUNCTOR: 12 00 00 00 04 24 6f 28 10 91 8e 00 00 00 00 00 
I (44369) FUNCTOR: 00 04 
E (44369) FUNCTOR: In notify callback. Attempting to read the message with the message handler
msg size: 18
E (44379) FUNCTOR: In notify callback: read: 22  bytes
E (44389) FUNCTOR: In notify callback. Handling the message with the message handler
Ho un totale di m_rx_entries: 1[unserialize] received id no. 04
E (44399) GATT_CLIENT: Adding ping_data_t element to the ping response list
E (44409) GATT_SERVER: In write characteristic task. policy is: 0 

Il client riceve come notifica  12 00 00 00 04 24 6f 28 10 91 8e 00 00 00 00 00 00 04   con tutti e 6 i bytes relativi al source address a 0, mentre dovrebbe ricevere 12 00 00 00 04 24 6f 28 97 4c 32 24 6f 28 10 91 8c 04 con 24 6f 28 10 91 8c  ad indicare il mac address.

La funzione ping_server definita in slave.cpp che costruisce il primo pacchetto da inviare è:

    ErrStatus Slave::ping_server(uint16_t gatt_if,uint8_t conn_id, uint8_t* mac_address,
                                uint8_t pong_flag){
        
        if(address == NULL)
            return GenericError;

        //Check if the mac address is in the routing table (robustness check).

        //Start pinging the server
        dev_addr_t src_addr = _build_dev_addr(get_dev_addr());
        dev_addr_t src_addr_;
        int j;
        for(j = 0; j<MAC_ADDRESS_SIZE; j++){
            src_address_to_send[j] = src_addr[j];
        }
        dev_addr_t dest_addr = _build_dev_addr(mac_address);

        RoutingPingMessage routing_ping_message(dest_addr,src_addr,pong_flag);
        uint8_t characteristic = IDX_CHAR_VAL_A;
        
        uint16_t* args = (uint16_t*)slave_message_extra_args;
        *args = gatt_if;
        uint8_t * _args = (uint8_t*) slave_message_extra_args;
        _args = (uint8_t*)(_args + sizeof(uint16_t));
        *_args = conn_id;
        _args = (uint8_t*)(_args + sizeof(uint8_t));
        *_args = characteristic;
        //ESP_LOGE(GATTC_TAG,"In ping transmission. src address is: ");
        //esp_log_buffer_hex(GATTC_TAG,get_dev_addr(),MAC_ADDRESS_SIZE);
        //ESP_LOGE(GATTC_TAG,"In ping transmission. dest_addr address is: ");
        //esp_log_buffer_hex(GATTC_TAG,mac_address,MAC_ADDRESS_SIZE);
        //First send the message into the buffer.
        ErrStatus  status = mes_handler.send((MessageHeader*)&routing_ping_message);
        if(status != Success){
            ESP_LOGE(GATTC_TAG,"In Slave::send_message. Error in MessageHandler::send");
            return status;
        }

            //Flush the output
        mes_handler.handle();
        return Success;
        
        //ErrStatus ret = send_message(gatt_if,conn_id,mac_address,(MessageHeader*)&routing_ping_message,characteristic);
        //if(ret != Success){
        //    ESP_LOGE(GATTC_TAG,"Error in sending the ping to the connected server");
        //}
        return Success;

    }

La funzione ping_transmission_callback  (la callback di invio associata al messaggio ROUTING_PING_ID) definita in slave.cpp

    void Slave::ping_transmission_callback(uint8_t* message, uint8_t size, MessageHeader* header_t,
                                            void * args)
    {
        //Check argument integrity
        if(message == NULL || header_t == NULL)
            return;
        if(size == 0)
            return;

        //ESP_LOGE(GATTC_TAG,"The ping message I'm about to transmit is");
        
       // esp_log_buffer_hex(GATTC_TAG,message,size);
        
        //ESP_LOGE(GATTC_TAG,"In ping transmission callback: we begin to retrieve the arguments");
        //Begin to parse the arguments
        uint16_t* ptr = (uint16_t*) args;
        uint16_t gattc_if = *ptr;
        uint8_t * _ptr = (uint8_t*)args;
        _ptr = (uint8_t*)(_ptr + sizeof(uint16_t));
        uint8_t conn_id = *(_ptr);
        _ptr = (uint8_t*)(_ptr + sizeof(uint8_t));
        uint8_t characteristic = *(_ptr);
        //ESP_LOGE(GATTC_TAG,"In ping transmission callback: we ended to retrieve the arguments");
       
        write_policy_t policy  = Standard;
        ErrStatus ret_status = write_characteristic(characteristic,message,size,gattc_if,
                                conn_id, policy);
        if(ret_status != Success){
            ESP_LOGE(GATTC_TAG,"In ping transmission callback: %d",ret_status);
        }
        return;

    }

La funzione received_packet_callback, invocata ogni volta che viene scritto qualche valore su una caratteristica e definita in callbacks.cpp è;

     //It will trigger the correct message callback.
    void Callback::received_packet_callback(uint8_t* packet,uint16_t size){
        if(!packet )
            return;
        std::cout<<"Received a packet"<<std::endl;
        esp_log_buffer_hex(FUNCTOR_TAG,packet,size);
        //Read the packet.
        //master_instance->parse_message_receive(packet,size);
        std::size_t bytes_read = master_instance->get_message_handler()->read(packet);
        if(bytes_read != size){
            ESP_LOGE(GATTS_TAG,"In Master::parse_message_receive. Expected to read: %d bytes     but %d actually read",size, bytes_read);
        }

        master_instance->get_message_handler()->handle();
        return;
    }

la funzione MessageHandler::handle() chiamata in questa funzione, invoca la funzione ping_reception_callback definita in master.cpp

        
    void Master::ping_reception_callback(MessageHeader* header_t,void * args){
        //ESP_LOGE(GATTS_TAG,"In ping reception callback");
        //Notify to all clients of the ping message.
        uint8_t pong_flag;
        RoutingPingMessage* rt_ping_message = (RoutingPingMessage*)header_t;
        

        ESP_LOGE(GATTS_TAG,"In ping reception callback: dest_address is");
        int j;
        uint8_t address_[MAC_ADDRESS_SIZE];
        dev_addr_t addr = rt_ping_message->destination();
        for(j = 0; j<MAC_ADDRESS_SIZE;++j){
            address_[j] = rt_ping_message->destination()[j];
        }
        esp_log_buffer_hex(GATTS_TAG,address_,MAC_ADDRESS_SIZE);

        ESP_LOGE(GATTS_TAG,"In ping reception callback: src_address is");

        for(j = 0; j<MAC_ADDRESS_SIZE;++j){
            address_[j] = rt_ping_message->source()[j];
        }
        esp_log_buffer_hex(GATTS_TAG,address_,MAC_ADDRESS_SIZE);

       
        if(rt_ping_message->pong_flag() == PONG_FLAG_VALUE)
            pong_flag = PONG_FLAG_VALUE;
        else
            pong_flag = PING_FLAG_VALUE;
        uint8_t * server_connids = get_server_connids();
        int i;
        for(i = 0; i<TOTAL_NUMBER_LIMIT; ++i){
            if(server_connids[i] == 1){
                if(get_type_connection(i) == CLIENT){
                    uint8_t * client_address = get_connid_MAC(i);
                    dev_addr_t cl_addr = _build_dev_addr(client_address);
                    RoutingPingMessage client_ping_message(cl_addr,rt_ping_message->source(),pong_flag);
                    uint8_t notify = NOTIFY_YES;

                    //ESP_LOGE(GATTS_TAG,"In ping reception callback: beginning to parse all arguments");

                    uint16_t* ptr = (uint16_t*) args;
                    *ptr = 0;
                    uint8_t * _ptr = (uint8_t*)args;
                    _ptr = (uint8_t*) (_ptr + sizeof(uint16_t));
                    *_ptr = i;
                    _ptr = (uint8_t*)(_ptr + sizeof(uint8_t));
                    *_ptr = 0;
                    _ptr = (uint8_t*)(_ptr + sizeof(uint8_t*));
                    *_ptr = notify;

                    //ESP_LOGE(GATTS_TAG,"In ping reception callback: ended to parse all arguments");

                    ESP_LOGE(GATTS_TAG,"Pinging client: %d ",i);

                    ErrStatus write_ret = mes_handler.send((MessageHeader*)&client_ping_message);
                    if(write_ret != Success){
                        ESP_LOGE(GATTS_TAG,"Error in sending the message to notify the client: %d ",i);
                    }
                    else{
                        mes_handler.handle();
                    }

                    }
                }
         }
        

        //Ping all neighbour servers
        for(auto it = neighbours.begin(); it != neighbours.end(); ++it){
            connected_server_params_t server = *it;
            uint16_t  gatt_if = server.gatt_if;
            uint8_t conn_id = server.conn_id;
            uint8_t server_id = server.server_id;
            uint8_t notify = NOTIFY_NO;

            dev_addr_t dest_addr = server.server_mac_address;

            RoutingPingMessage new_routing_ping_message(dest_addr,rt_ping_message->source(),pong_flag);

            ESP_LOGE(GATTS_TAG,"In ping reception callback: beginning to parse all arguments");

            uint16_t* ptr = (uint16_t*) args;
            *ptr = gatt_if;
            uint8_t * _ptr = (uint8_t*) args;
            _ptr = (uint8_t*) (_ptr + sizeof(uint16_t));
            *_ptr = conn_id;
            _ptr = (uint8_t*)(_ptr + sizeof(uint8_t));
            *_ptr = server_id;
            _ptr = (uint8_t*)(_ptr + sizeof(uint8_t*));
            *_ptr = notify;

            ESP_LOGE(GATTS_TAG,"In ping reception callback: ended to parse all arguments");
            
            ESP_LOGE(GATTS_TAG, "Sending ping to the neighbour: ");
            uint8_t _addr[MAC_ADDRESS_SIZE];
            int i;
            for(i =0; i<MAC_ADDRESS_SIZE; i++){
                _addr[i] = dest_addr[i];
            }
            esp_log_buffer_hex(GATTS_TAG,_addr,MAC_ADDRESS_SIZE);
            if(server_id == SERVER_S1 || server_id == SERVER_S2 || server_id == SERVER_S3){
                ErrStatus status = mes_handler.send((MessageHeader*)&new_routing_ping_message);
                if(status != Success){
                    ESP_LOGE(GATTS_TAG,"Error in sending ping to server: %d",server_id);
                    esp_log_buffer_hex(GATTS_TAG,_addr,MAC_ADDRESS_SIZE);
                }
                else{
                    mes_handler.handle();
                }
            }

        }
        
        
        

        return;
    }

        return;
    }

**Comment by DelVecchioAndrea** [comment]
Io e @EmanueleGiacomini abbiamo ipotizzato potesse anche  trattarsi di un problema delle funzioni di kernel.c, in particolare:
write_CHR
notify_client

**Comment by EmanueleGiacomini** [comment]
Il bug è stato risolto dalla commit 35ea7c1c8aefa90185031296ff3b5ab0a17fcc46 
il dest address veniva sostituito dal source address e il secondo rimaneva non inizializzato.
Tra l'altro l'errore era propagato su tutti i pacchetti, dunque ora dovrebbe essere risolto
