### ISSUE TITLE
Toolchain idf.py in a bad branch

### ISSUE THREAD

**Issue by Thecave3** [BE-Mesh/esp32-ble-mesh#36]
The current version of idf.py toolchain used by the program is in a release candidate of 4.0 version. This version is highly unstable and as long as the new stable release comes out we must update of toolchain to it.

Unless new communications from the esp32 maintainers the official link to install the toolchain is https://docs.espressif.com/projects/esp-idf/en/v4.0-rc/get-started/index.html .

**Comment by EmanueleGiacomini** [comment]
Tested lastest ESP32 Toolchain version and no issues appeared.
